if(NOT DEFINED METRICS_FILE)
    message(FATAL_ERROR "METRICS_FILE is required.")
endif()

if(NOT EXISTS "${METRICS_FILE}")
    message(FATAL_ERROR "Host metrics file does not exist: ${METRICS_FILE}")
endif()

file(STRINGS "${METRICS_FILE}" metrics_lines)
list(LENGTH metrics_lines line_count)
if(line_count LESS 3)
    message(FATAL_ERROR "Host metrics must contain a header and at least two samples.")
endif()

list(REMOVE_AT metrics_lines 0)
set(expected_present_count "")
foreach(line IN LISTS metrics_lines)
    string(REPLACE "," ";" columns "${line}")
    list(LENGTH columns column_count)
    if(column_count LESS 8)
        message(FATAL_ERROR "Host metrics row has fewer than eight columns: ${line}")
    endif()

    list(GET columns 5 present_count)
    if(expected_present_count STREQUAL "")
        set(expected_present_count "${present_count}")
        if(expected_present_count LESS 1)
            message(FATAL_ERROR "Host did not present an initial overlay frame.")
        endif()
    elseif(NOT present_count STREQUAL expected_present_count)
        message(FATAL_ERROR "Host presented repeatedly while the overlay state was unchanged.")
    endif()
endforeach()
